# -*- coding: utf-8 -*-
"""stanford final project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15uX-snc8LOlZxzWlHyWxEjbp-JTJap1f
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_excel("comparison.xlsx")

df.head()

print(df.columns)

print(df.shape)

df.describe()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Features and target
X = df[["Bond Angle", "Bond Distance"]]
y = df["Entanglement"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

models = {
    "Linear Regression": LinearRegression(),
    "Polynomial Regression": make_pipeline(
        PolynomialFeatures(degree=3),
        LinearRegression()
    ),
    "Random Forest": RandomForestRegressor(
        n_estimators=200,
        random_state=42
    )
}

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    r2 = r2_score(y_test, pred)

    print(f"{name}: R² = {r2:.4f}")

from sklearn.ensemble import RandomForestRegressor

best_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

best_model.fit(X_train, y_train)

import pandas as pd

def predict_entanglement(angle, distance):

    sample = pd.DataFrame({
        "Bond Angle": [angle],
        "Bond Distance": [distance]
    })

    return best_model.predict(sample)[0]

def predict_entanglement(angle, distance):
    return best_model.predict([[angle, distance]])[0]

value = predict_entanglement(104.5, 0.96)

print(value)

from ipywidgets import interact
import pandas as pd

@interact(
    angle=(35.87,180.87,1),
    distance=(0.75,2.15,0.05)
)
def predictor(angle=104.5, distance=0.96):

    sample = pd.DataFrame({
        "Bond Angle":[angle],
        "Bond Distance":[distance]
    })

    value = best_model.predict(sample)[0]

    print(f"Bond Angle      : {angle:.2f}°")
    print(f"Bond Distance   : {distance:.2f} Å")
    print(f"Entanglement ξ  : {value:.6f}")

import matplotlib.pyplot as plt

pivot = df.pivot(
    index="Bond Distance",
    columns="Bond Angle",
    values="Entanglement"
)

plt.figure(figsize=(10,6))

extent = [
    pivot.columns.min(),
    pivot.columns.max(),
    pivot.index.min(),
    pivot.index.max()
]

plt.imshow(
    pivot,
    aspect='auto',
    origin='lower',
    extent=extent
)

plt.colorbar(label='Entanglement ξ')

plt.xlabel("Bond Angle (degrees)")
plt.ylabel("Bond Distance (Å)")
plt.title("Quantum Entanglement Landscape of Water")

plt.show()

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

@interact(
    angle=(35.87,180.87,1),
    distance=(0.75,2.15,0.05)
)
def visualize(angle=104.5, distance=0.96):

    theta = np.radians(angle)

    O = np.array([0,0])

    H1 = np.array([distance,0])

    H2 = np.array([
        distance*np.cos(theta),
        distance*np.sin(theta)
    ])

    sample = pd.DataFrame({
        "Bond Angle":[angle],
        "Bond Distance":[distance]
    })

    ent = best_model.predict(sample)[0]

    plt.figure(figsize=(6,6))

    plt.plot([O[0],H1[0]],[O[1],H1[1]],linewidth=3)
    plt.plot([O[0],H2[0]],[O[1],H2[1]],linewidth=3)

    plt.scatter(O[0],O[1],s=400)
    plt.scatter(H1[0],H1[1],s=200)
    plt.scatter(H2[0],H2[1],s=200)

    plt.text(O[0],O[1],"O",fontsize=14)
    plt.text(H1[0],H1[1],"H",fontsize=14)
    plt.text(H2[0],H2[1],"H",fontsize=14)

    plt.title(
        f"Angle={angle:.1f}°   Distance={distance:.2f} Å\n"
        f"Predicted Entanglement ξ={ent:.6f}"
    )

    plt.axis('equal')
    plt.grid(True)

    plt.show()

import joblib

joblib.dump(best_model, "entanglement_model.pkl")



from google.colab import files

files.download("entanglement_model.pkl")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from ipywidgets import interact

pivot = df.pivot(
    index="Bond Distance",
    columns="Bond Angle",
    values="Entanglement"
)

@interact(
    angle=(35.87,180.87,1),
    distance=(0.75,2.15,0.05)
)
def dashboard(angle=104.5, distance=0.96):

    sample = pd.DataFrame({
        "Bond Angle":[angle],
        "Bond Distance":[distance]
    })

    ent = best_model.predict(sample)[0]

    theta = np.radians(angle)

    O = np.array([0,0])
    H1 = np.array([distance,0])

    H2 = np.array([
        distance*np.cos(theta),
        distance*np.sin(theta)
    ])

    fig, (ax1, ax2) = plt.subplots(
        1,
        2,
        figsize=(12,5)
    )

    # HEATMAP

    extent = [
        pivot.columns.min(),
        pivot.columns.max(),
        pivot.index.min(),
        pivot.index.max()
    ]

    im = ax1.imshow(
        pivot,
        aspect='auto',
        origin='lower',
        extent=extent
    )

    ax1.scatter(
        angle,
        distance,
        s=150,
        marker='*'
    )

    ax1.set_title("Entanglement Landscape")
    ax1.set_xlabel("Bond Angle (°)")
    ax1.set_ylabel("Bond Distance (Å)")

    # MOLECULE

    ax2.plot(
        [O[0],H1[0]],
        [O[1],H1[1]],
        linewidth=3
    )

    ax2.plot(
        [O[0],H2[0]],
        [O[1],H2[1]],
        linewidth=3
    )

    ax2.scatter(O[0],O[1],s=1000)
    ax2.scatter(H1[0],H1[1],s=500)
    ax2.scatter(H2[0],H2[1],s=500)

    ax2.text(O[0],O[1],"O")
    ax2.text(H1[0],H1[1],"H")
    ax2.text(H2[0],H2[1],"H")

    ax2.set_title(
        f"ξ = {ent:.6f}"
    )

    ax2.axis("equal")

    plt.tight_layout()
    plt.show()

plt.style.use('dark_background')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from ipywidgets import interact

# Dark theme
plt.style.use("dark_background")

# Heatmap data
pivot = df.pivot(
    index="Bond Distance",
    columns="Bond Angle",
    values="Entanglement"
)

# Entanglement range
emin = df["Entanglement"].min()
emax = df["Entanglement"].max()

@interact(
    angle=(35.87,180.87,1),
    distance=(0.75,2.15,0.05)
)
def quantum_entanglement_explorer(
    angle=104.5,
    distance=0.96
):

    # Prediction
    sample = pd.DataFrame({
        "Bond Angle":[angle],
        "Bond Distance":[distance]
    })

    ent = best_model.predict(sample)[0]

    # Geometry
    theta = np.radians(angle)

    O = np.array([0,0])

    H1 = np.array([distance,0])

    H2 = np.array([
        distance*np.cos(theta),
        distance*np.sin(theta)
    ])

    # Molecule color depends on entanglement
    norm = (ent - emin)/(emax - emin)
    molecule_color = plt.cm.plasma(norm)

    # Dashboard
    fig, (ax1, ax2) = plt.subplots(
        1,
        2,
        figsize=(14,6)
    )

    fig.suptitle(
        "Quantum Entanglement Explorer",
        fontsize=18,
        fontweight="bold"
    )

    # -------------------------
    # LEFT PANEL: HEATMAP
    # -------------------------

    extent = [
        pivot.columns.min(),
        pivot.columns.max(),
        pivot.index.min(),
        pivot.index.max()
    ]

    im = ax1.imshow(
        pivot,
        aspect="auto",
        origin="lower",
        extent=extent,
        cmap="plasma"
    )

    ax1.scatter(
        angle,
        distance,
        s=250,
        marker="*",
        color="white",
        label="Current Geometry"
    )

    ax1.scatter(
        104.5,
        0.96,
        s=120,
        marker="o",
        color="cyan",
        label="Equilibrium Water"
    )

    ax1.set_title("Entanglement Landscape")

    ax1.set_xlabel("Bond Angle (°)")
    ax1.set_ylabel("Bond Distance (Å)")

    ax1.legend()

    cbar = fig.colorbar(
        im,
        ax=ax1
    )

    cbar.set_label("Entanglement ξ")

    # -------------------------
    # RIGHT PANEL: MOLECULE
    # -------------------------

    ax2.plot(
        [O[0],H1[0]],
        [O[1],H1[1]],
        linewidth=5,
        color="white"
    )

    ax2.plot(
        [O[0],H2[0]],
        [O[1],H2[1]],
        linewidth=5,
        color="white"
    )

    ax2.scatter(
        O[0],
        O[1],
        s=1800,
        color=molecule_color,
        edgecolors="white"
    )

    ax2.scatter(
        H1[0],
        H1[1],
        s=900,
        color="lightgray",
        edgecolors="white"
    )

    ax2.scatter(
        H2[0],
        H2[1],
        s=900,
        color="lightgray",
        edgecolors="white"
    )

    ax2.text(
        O[0],
        O[1],
        "O",
        fontsize=16,
        ha="center",
        va="center"
    )

    ax2.text(
        H1[0],
        H1[1],
        "H",
        fontsize=14,
        ha="center",
        va="center"
    )

    ax2.text(
        H2[0],
        H2[1],
        "H",
        fontsize=14,
        ha="center",
        va="center"
    )

    ax2.set_title(
        f"""
Predicted Entanglement

ξ = {ent:.6f}

Angle = {angle:.1f}°
Distance = {distance:.2f} Å
"""
    )

    ax2.axis("equal")
    ax2.grid(alpha=0.2)

    plt.figtext(
        0.5,
        0.02,
        "Machine-learning prediction of quantum entanglement in water molecules",
        ha="center",
        fontsize=10
    )

    plt.tight_layout()

    plt.show()

df
best_model

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from ipywidgets import interact

# =========================
# STYLE
# =========================

plt.style.use("dark_background")

# =========================
# HEATMAP DATA
# =========================

pivot = df.pivot(
    index="Bond Distance",
    columns="Bond Angle",
    values="Entanglement"
)

emin = df["Entanglement"].min()
emax = df["Entanglement"].max()

# =========================
# DASHBOARD
# =========================

@interact(
    angle=(35.87, 180.87, 1),
    distance=(0.75, 2.15, 0.05)
)
def quantum_entanglement_explorer(
    angle=104.5,
    distance=0.96
):

    # ---------------------
    # Prediction
    # ---------------------

    sample = pd.DataFrame({
        "Bond Angle": [angle],
        "Bond Distance": [distance]
    })

    ent = best_model.predict(sample)[0]

    ent_percent = 100 * (ent - emin) / (emax - emin)

    # ---------------------
    # Water Geometry
    # ---------------------

    theta = np.radians(angle)

    O = np.array([0, 0])

    H1 = np.array([distance, 0])

    H2 = np.array([
        distance * np.cos(theta),
        distance * np.sin(theta)
    ])

    # ---------------------
    # Nearest Actual Point
    # ---------------------

    idx = (
        (df["Bond Angle"] - angle)**2 +
        (df["Bond Distance"] - distance)**2
    ).idxmin()

    nearest = df.loc[idx]

    actual_ent = nearest["Entanglement"]

    error = abs(actual_ent - ent)

    # ---------------------
    # Molecule Color
    # ---------------------

    norm = (ent - emin) / (emax - emin)

    mol_color = plt.cm.plasma(norm)

    # ---------------------
    # Figure Layout
    # ---------------------

    fig = plt.figure(figsize=(16, 8))

    fig.suptitle(
        "Quantum Entanglement Explorer\n"
        "Machine Learning Assisted Prediction of Molecular Entanglement",
        fontsize=20,
        fontweight="bold"
    )

    ax1 = plt.subplot2grid((1, 2), (0, 0))
    ax2 = plt.subplot2grid((1, 2), (0, 1))

    # =====================================================
    # LEFT PANEL
    # =====================================================

    extent = [
        pivot.columns.min(),
        pivot.columns.max(),
        pivot.index.min(),
        pivot.index.max()
    ]

    im = ax1.imshow(
        pivot,
        aspect="auto",
        origin="lower",
        extent=extent,
        cmap="plasma"
    )

    ax1.scatter(
        angle,
        distance,
        s=550,
        marker="*",
        color="white",
        edgecolors="black",
        linewidths=2,
        label="Current Geometry"
    )

    ax1.scatter(
        104.5,
        0.96,
        s=180,
        color="cyan",
        edgecolors="white",
        linewidths=1.5,
        label="Equilibrium Water"
    )

    ax1.set_title(
        "Quantum Entanglement Landscape",
        fontsize=14,
        fontweight="bold"
    )

    ax1.set_xlabel("Bond Angle (°)", fontsize=12)
    ax1.set_ylabel("Bond Distance (Å)", fontsize=12)

    ax1.legend()

    cbar = fig.colorbar(im, ax=ax1)

    cbar.set_label(
        "Entanglement ξ",
        fontsize=11
    )

    # =====================================================
    # RIGHT PANEL
    # =====================================================

    ax2.plot(
        [O[0], H1[0]],
        [O[1], H1[1]],
        linewidth=6,
        color="white"
    )

    ax2.plot(
        [O[0], H2[0]],
        [O[1], H2[1]],
        linewidth=6,
        color="white"
    )

    ax2.scatter(
        O[0],
        O[1],
        s=2500,
        color=mol_color,
        edgecolors="white",
        linewidths=2
    )

    ax2.scatter(
        H1[0],
        H1[1],
        s=1200,
        color="lightgray",
        edgecolors="white",
        linewidths=2
    )

    ax2.scatter(
        H2[0],
        H2[1],
        s=1200,
        color="lightgray",
        edgecolors="white",
        linewidths=2
    )

    ax2.text(
        O[0],
        O[1],
        "O",
        fontsize=18,
        ha="center",
        va="center",
        fontweight="bold"
    )

    ax2.text(
        H1[0],
        H1[1],
        "H",
        fontsize=16,
        ha="center",
        va="center",
        fontweight="bold"
    )

    ax2.text(
        H2[0],
        H2[1],
        "H",
        fontsize=16,
        ha="center",
        va="center",
        fontweight="bold"
    )

    ax2.set_xlim(-1.6, 1.6)
    ax2.set_ylim(-1.2, 1.6)

    ax2.set_aspect("equal")

    ax2.grid(alpha=0.2)

    ax2.set_title(
        f"Predicted Entanglement ξ = {ent:.6f}",
        fontsize=15,
        fontweight="bold"
    )

    # ---------------------
    # Information Panel
    # ---------------------

    info = (
        f"Entanglement Level : {ent_percent:.1f}%\n\n"
        f"Bond Angle         : {angle:.1f}°\n"
        f"Bond Distance      : {distance:.2f} Å\n\n"
        f"Nearest Actual ξ   : {actual_ent:.6f}\n"
        f"Prediction Error   : {error:.6f}"
    )

    ax2.text(
        0,
        1.35,
        info,
        fontsize=12,
        ha="center",
        va="top",
        bbox=dict(
            boxstyle="round,pad=0.6",
            facecolor="black",
            edgecolor="white",
            alpha=0.8
        )
    )

    # ---------------------
    # Footer
    # ---------------------

    plt.figtext(
        0.5,
        0.02,
        "Random Forest Regression | R² = 0.9221 | 450 Quantum-Chemistry Geometries",
        ha="center",
        fontsize=11
    )

    plt.tight_layout(rect=[0, 0.04, 1, 0.93])

    plt.show()

import joblib

joblib.dump(best_model, "entanglement_model.pkl")

from google.colab import files

files.download("entanglement_model.pkl")

!pip install streamlit



import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

# ==========================
# PAGE SETTINGS
# ==========================

st.set_page_config(
    page_title="Quantum Entanglement Explorer",
    layout="wide"
)

# ==========================
# LOAD MODEL & DATA
# ==========================

model = joblib.load("entanglement_model.pkl")

df = pd.read_excel("comparison.xlsx")

pivot = df.pivot(
    index="Bond Distance",
    columns="Bond Angle",
    values="Entanglement"
)

emin = df["Entanglement"].min()
emax = df["Entanglement"].max()

# ==========================
# TITLE
# ==========================

st.title("🔬 Quantum Entanglement Explorer")

st.markdown(
"""
Machine Learning Assisted Prediction of Molecular Entanglement in Water Molecules
"""
)

# ==========================
# SIDEBAR CONTROLS
# ==========================

st.sidebar.header("Geometry Controls")

angle = st.sidebar.slider(
    "Bond Angle (°)",
    float(df["Bond Angle"].min()),
    float(df["Bond Angle"].max()),
    104.5
)

distance = st.sidebar.slider(
    "Bond Distance (Å)",
    float(df["Bond Distance"].min()),
    float(df["Bond Distance"].max()),
    0.96
)

# ==========================
# PREDICTION
# ==========================

sample = pd.DataFrame({
    "Bond Angle": [angle],
    "Bond Distance": [distance]
})

ent = model.predict(sample)[0]

st.metric(
    "Predicted Entanglement ξ",
    f"{ent:.6f}"
)

# ==========================
# LAYOUT
# ==========================

col1, col2 = st.columns(2)

# ====================================
# HEATMAP
# ====================================

with col1:

    fig1, ax1 = plt.subplots(figsize=(6,5))

    extent = [
        pivot.columns.min(),
        pivot.columns.max(),
        pivot.index.min(),
        pivot.index.max()
    ]

    im = ax1.imshow(
        pivot,
        aspect="auto",
        origin="lower",
        extent=extent,
        cmap="plasma"
    )

    ax1.scatter(
        angle,
        distance,
        s=350,
        marker="*",
        color="white"
    )

    ax1.scatter(
        104.5,
        0.96,
        s=120,
        color="cyan"
    )

    ax1.set_title("Entanglement Landscape")
    ax1.set_xlabel("Bond Angle (°)")
    ax1.set_ylabel("Bond Distance (Å)")

    fig1.colorbar(
        im,
        ax=ax1,
        label="Entanglement ξ"
    )

    st.pyplot(fig1)

# ====================================
# MOLECULE
# ====================================

with col2:

    theta = np.radians(angle)

    O = np.array([0, 0])

    H1 = np.array([distance, 0])

    H2 = np.array([
        distance*np.cos(theta),
        distance*np.sin(theta)
    ])

    fig2, ax2 = plt.subplots(figsize=(6,5))

    ax2.plot(
        [O[0], H1[0]],
        [O[1], H1[1]],
        linewidth=5
    )

    ax2.plot(
        [O[0], H2[0]],
        [O[1], H2[1]],
        linewidth=5
    )

    ax2.scatter(
        O[0],
        O[1],
        s=2500
    )

    ax2.scatter(
        H1[0],
        H1[1],
        s=1200
    )

    ax2.scatter(
        H2[0],
        H2[1],
        s=1200
    )

    ax2.text(O[0], O[1], "O")
    ax2.text(H1[0], H1[1], "H")
    ax2.text(H2[0], H2[1], "H")

    ax2.set_aspect("equal")

    ax2.set_title(
        f"Water Geometry\nξ = {ent:.6f}"
    )

    st.pyplot(fig2)

# ==========================
# MODEL INFO
# ==========================

st.markdown("---")

st.subheader("Model Information")

st.write("Random Forest Regression")

st.write("R² Score: 0.9221")

st.write("Training Data: 450 molecular geometries")